export type DishStyle = {
  name: string;
  idealHeat: number;
  flavor: string;
  quality: number;
};

export type Dish = {
  id: number;
  name: string;
  category: string;
  price: number;
  desc: string;
  ingredients: string[];
  techniques?: string[];
  styles?: DishStyle[];
};

export const INGREDIENT_PRICES: Record<string, number> = {
  番茄: 3,
  鸡蛋: 3,
  盐: 1,
  白糖: 1,
  土豆: 3,
  辣椒: 2,
  醋: 2,
  猪肉: 6,
  木耳: 3,
  胡萝卜: 2,
  泡椒: 2,
  鸡胸肉: 6,
  花生: 2,
  干辣椒: 2,
  黄瓜: 2,
  嫩豆腐: 3,
  牛肉末: 6,
  豆瓣酱: 2,
  花椒: 2,
  青椒: 2,
  蒜: 1,
  生抽: 2,
  五花肉: 7,
  冰糖: 2,
  老抽: 2,
  八角: 2,
  猪肋排: 8,
  鸡翅: 7,
  可乐: 2,
  姜: 1,
  瘦肉: 6,
  豆芽: 2,
  蒜苗: 2,
  甜面酱: 2,
  鲈鱼: 12,
  姜丝: 1,
  葱: 1,
  蒸鱼豉油: 2,
  大虾: 12,
  粉丝: 3,
  大蒜: 1,
  鸡块: 7,
  白芝麻: 2,
  鸡腿肉: 7,
  干香菇: 3,
  蚝油: 2,
  梅菜干: 3,
  梅菜: 3,
  剁椒: 3,
  鱼头: 10,
  温水: 0,
  紫菜: 2,
  香油: 2,
  牛肉: 8,
  洋葱: 2,
  排骨: 8,
  冬瓜: 3,
  姜片: 1,
  豆腐: 3,
  肉丝: 6,
  羊肉: 9,
  白萝卜: 3,
  枸杞: 3,
  青菜: 2,
  油麦菜: 2,
  干木耳: 3,
  小米辣: 2,
  牛腱子: 10,
  香菜: 2,
  辣椒油: 2,
  食用油: 2,
  老豆腐: 3,
  胡椒粉: 1,
  面条: 3,
  小葱: 1,
  米饭: 2,
  面粉: 2,
  白菜: 2,
  番茄酱: 1,
  梅干菜: 3,
  牛腩: 6,
  鸡腿: 5,
  蘑菇: 3,
  黄豆: 2,
  香菇: 3,
  蛋白: 2,
  猪肝: 6,
  西红柿: 3,
  豆皮: 2,
  青豆: 2,
  里脊: 7,
  姜汁: 1,
  蛋黄: 2,
  地瓜: 3,
  奶油: 3,
  鲫鱼: 10,
  油条: 2,
  豆角: 2,
  空心菜: 2,
  茄子: 2,
  黄油: 4,
  橄榄油: 3,
  大豆油: 2,
  奶酪: 4,
  意面: 3,
  牛排: 10,
  吐司: 2,
  培根: 5,
  西兰花: 3,
  香草: 2,
  马铃薯: 3,
  黑胡椒: 1,
  欧芹: 2,
  柠檬: 2,
  火腿: 4,
  法棍: 2,
  面包: 2,
  牛奶: 2,
  小番茄: 2,
  孜然: 1,
  羊排: 9,
  白葡萄酒: 3,
  火鸡胸: 8,
  火鸡腿: 9,
  玉米: 2,
  龙虾: 16,
  扇贝: 8,
  猪排: 8,
  花生油: 2,
  南瓜: 3,
  锅巴: 2,
  蛤蜊: 6,
  白胡椒: 1,
  榴莲: 8,
  咖喱粉: 2
};

export const EMOJIS: Record<string, string> = {
  番茄: "🍅",
  鸡蛋: "🥚",
  土豆: "🥔",
  猪肉: "🥩",
  鸡胸肉: "🍗",
  五花肉: "🥩",
  鸡翅: "🍗",
  鲈鱼: "🐟",
  大虾: "🦐",
  牛肉: "🥩",
  羊肉: "🍖",
  黄瓜: "🥒",
  青椒: "🫑",
  胡萝卜: "🥕",
  豆腐: "🧈",
  嫩豆腐: "🧈",
  老豆腐: "🧈",
  米饭: "🍚",
  面条: "🍜",
  面粉: "🌾",
  白菜: "🥬",
  青菜: "🥬",
  油麦菜: "🥬",
  冬瓜: "🥒",
  白萝卜: "🥕",
  豆芽: "🌱",
  木耳: "🍄",
  干木耳: "🍄",
  干香菇: "🍄",
  紫菜: "🌿",
  花生: "🥜",
  辣椒: "🌶️",
  干辣椒: "🌶️",
  小米辣: "🌶️",
  泡椒: "🌶️",
  葱: "🧅",
  小葱: "🧅",
  洋葱: "🧅",
  蒜: "🧄",
  大蒜: "🧄",
  蒜苗: "🌿",
  姜: "🫚",
  姜丝: "🫚",
  姜片: "🫚",
  香菜: "🌿",
  花椒: "🫘",
  八角: "⭐",
  白糖: "🍬",
  冰糖: "🍬",
  盐: "🧂",
  醋: "🧴",
  生抽: "🧴",
  老抽: "🧴",
  豆瓣酱: "🥫",
  甜面酱: "🥫",
  蚝油: "🥫",
  剁椒: "🌶️",
  蒸鱼豉油: "🥫",
  食用油: "🫗",
  香油: "🫗",
  辣椒油: "🌶️",
  胡椒粉: "🧂",
  白芝麻: "⚪",
  粉丝: "🍜",
  可乐: "🥤",
  温水: "💧",
  枸杞: "🔴",
  梅干菜: "🥬",
  梅菜干: "🥬",
  番茄酱: "🥫",
  牛肉末: "🥩",
  瘦肉: "🥩",
  肉丝: "🥩",
  猪肋排: "🍖",
  排骨: "🍖",
  鸡块: "🍗",
  鸡腿肉: "🍗",
  牛腱子: "🥩",
  鱼头: "🐟",
  牛腩: "🥩",
  鸡腿: "🍗",
  蘑菇: "🍄",
  黄豆: "🫘",
  香菇: "🍄",
  蛋白: "🥚",
  猪肝: "🥩",
  西红柿: "🍅",
  豆皮: "🧈",
  青豆: "🫛",
  里脊: "🥩",
  姜汁: "🫚",
  蛋黄: "🥚",
  地瓜: "🍠",
  奶油: "🥛",
  鲫鱼: "🐟",
  油条: "🥞",
  豆角: "🫘",
  空心菜: "🥬",
  茄子: "🍆",
  黄油: "🧈",
  橄榄油: "🫒",
  大豆油: "🫒",
  奶酪: "🧀",
  意面: "🍝",
  牛排: "🥩",
  吐司: "🍞",
  培根: "🥓",
  西兰花: "🥦",
  香草: "🌿",
  马铃薯: "🥔",
  黑胡椒: "⚫",
  欧芹: "🌿",
  柠檬: "🍋",
  火腿: "🥩",
  法棍: "🥖",
  面包: "🥖",
  牛奶: "🥛",
  小番茄: "🍅",
  孜然: "🌾",
  羊排: "🍖",
  白葡萄酒: "🍷",
  火鸡胸: "🦃",
  火鸡腿: "🦃",
  玉米: "🌽",
  龙虾: "🦞",
  扇贝: "🐚",
  猪排: "🥩",
  花生油: "🫗",
  南瓜: "🎃",
  锅巴: "🍘",
  蛤蜊: "🐚",
  白胡椒: "⚪",
  榴莲: "🍈",
  咖喱粉: "🟡"
};

export const COOKING_TECHNIQUES = ["煎", "烤", "爆炒", "炖", "焖", "炸", "蒸", "烧"];

export const CATEGORIES = ["全部", "家常菜", "硬菜", "蒸菜", "汤类", "小炒", "西餐", "西式主食", "汤品", "海鲜", "自由菜"];

export const DISHES: Dish[] = [
  { id: 1, name: "番茄炒蛋", category: "家常菜", price: 12, desc: "酸甜开胃的经典下饭菜，汤汁浓郁。", ingredients: ["番茄", "鸡蛋", "盐", "白糖"], techniques: ["煎", "爆炒"] },
  { id: 2, name: "酸辣土豆丝", category: "家常菜", price: 10, desc: "脆爽土豆丝，酸辣爽口。", ingredients: ["土豆", "辣椒", "醋", "盐"], techniques: ["爆炒", "煎"] },
  { id: 3, name: "鱼香肉丝", category: "家常菜", price: 18, desc: "咸甜酸辣，肉丝搭配木耳胡萝卜。", ingredients: ["猪肉", "木耳", "胡萝卜", "泡椒"], techniques: ["爆炒", "煎"] },
  { id: 4, name: "宫保鸡丁", category: "家常菜", price: 19, desc: "鸡丁配花生，微甜微辣，香酥。", ingredients: ["鸡胸肉", "花生", "干辣椒", "黄瓜"], techniques: ["爆炒", "煎"] },
  { id: 5, name: "麻婆豆腐", category: "家常菜", price: 14, desc: "嫩豆腐裹麻辣酱汁，下饭。", ingredients: ["嫩豆腐", "牛肉末", "豆瓣酱", "花椒"], techniques: ["爆炒", "焖"] },
  { id: 6, name: "青椒炒肉", category: "家常菜", price: 15, desc: "青椒鲜辣，肉片软嫩。", ingredients: ["猪肉", "青椒", "蒜", "生抽"], techniques: ["爆炒", "煎"] },
  { id: 7, name: "红烧肉", category: "硬菜", price: 28, desc: "五花肉慢炖，肥而不腻。", ingredients: ["五花肉", "冰糖", "老抽", "八角"], techniques: ["炖", "焖"] },
  { id: 8, name: "糖醋排骨", category: "硬菜", price: 30, desc: "排骨酸甜，软糯入味。", ingredients: ["猪肋排", "冰糖", "醋", "生抽"], techniques: ["煎", "炖"] },
  { id: 9, name: "可乐鸡翅", category: "硬菜", price: 22, desc: "甜香鸡翅，肉质多汁。", ingredients: ["鸡翅", "可乐", "姜", "生抽"], techniques: ["烤", "焖"] },
  { id: 10, name: "水煮肉片", category: "硬菜", price: 26, desc: "麻辣鲜香，肉片滑嫩。", ingredients: ["瘦肉", "豆芽", "辣椒", "花椒"], techniques: ["煎", "爆炒"] },
  { id: 11, name: "回锅肉", category: "硬菜", price: 24, desc: "五花肉配蒜苗，川味香辣。", ingredients: ["五花肉", "蒜苗", "豆瓣酱", "甜面酱"], techniques: ["爆炒", "煎"] },
  { id: 12, name: "清蒸鲈鱼", category: "硬菜", price: 32, desc: "鱼肉细嫩清淡，保留原味。", ingredients: ["鲈鱼", "姜丝", "葱", "蒸鱼豉油"], techniques: ["蒸", "焖"] },
  { id: 13, name: "蒜蓉粉丝蒸虾", category: "硬菜", price: 34, desc: "大虾搭配粉丝，蒜香浓郁。", ingredients: ["大虾", "粉丝", "大蒜", "生抽"], techniques: ["蒸", "爆炒"] },
  { id: 14, name: "辣子鸡", category: "硬菜", price: 27, desc: "干香鸡肉，辣椒爆炒。", ingredients: ["鸡块", "干辣椒", "花椒", "白芝麻"], techniques: ["爆炒", "煎"] },
  { id: 15, name: "香菇滑鸡", category: "蒸菜", price: 20, desc: "鸡肉香菇同蒸，汤汁醇厚。", ingredients: ["鸡腿肉", "干香菇", "姜", "蚝油"], techniques: ["蒸", "炖"] },
  { id: 16, name: "梅菜扣肉", category: "蒸菜", price: 29, desc: "五花肉搭配梅干菜，香气厚重。", ingredients: ["五花肉", "梅干菜", "老抽", "冰糖"], techniques: ["炖", "焖"] },
  { id: 17, name: "剁椒鱼头", category: "蒸菜", price: 33, desc: "鱼头铺上剁椒，鲜辣过瘾。", ingredients: ["鱼头", "剁椒", "姜", "蒜"], techniques: ["蒸", "煎"] },
  { id: 18, name: "蒸水蛋", category: "蒸菜", price: 9, desc: "蒸蛋顺滑，清淡营养。", ingredients: ["鸡蛋", "温水", "盐", "生抽"], techniques: ["蒸", "焖"] },
  { id: 19, name: "紫菜蛋花汤", category: "汤类", price: 11, desc: "温润鲜美，清爽提味。", ingredients: ["鸡蛋", "紫菜", "温水", "盐"], techniques: ["炖", "煎"] },
  { id: 20, name: "番茄豆腐汤", category: "汤类", price: 13, desc: "鲜甜番茄配嫩豆腐，温柔鲜亮。", ingredients: ["番茄", "豆腐", "温水", "盐"], techniques: ["炖", "焖"] },
  { id: 21, name: "西红柿牛腩", category: "汤类", price: 26, desc: "番茄香与牛腩嫩度的完美组合。", ingredients: ["牛腩", "西红柿", "姜", "洋葱"], techniques: ["炖", "焖"] },
  { id: 22, name: "豆腐火腿汤", category: "汤类", price: 15, desc: "豆腐清甜，火腿香浓。", ingredients: ["豆腐", "猪肉", "温水", "白糖"], techniques: ["炖", "焖"] },
  { id: 23, name: "咖喱牛肉", category: "小炒", price: 28, desc: "香浓咖喱汁裹住牛肉，暖胃又下饭。", ingredients: ["牛肉", "洋葱", "胡萝卜", "生抽"], techniques: ["爆炒", "煎"] },
  { id: 24, name: "番茄牛腩", category: "小炒", price: 27, desc: "番茄酸甜激发牛腩鲜美。", ingredients: ["牛腩", "番茄", "姜", "蒜"], techniques: ["焖", "炖"] },
  { id: 25, name: "香煎鲫鱼", category: "小炒", price: 31, desc: "鱼皮金脆，酥香迷人。", ingredients: ["鲫鱼", "姜", "蒜", "生抽"], techniques: ["煎", "烤"] },
  { id: 26, name: "奶油蘑菇", category: "小炒", price: 18, desc: "鲜香浓郁，奶香十足。", ingredients: ["蘑菇", "奶油", "盐", "胡椒粉"], techniques: ["爆炒", "煎"] },
  { id: 27, name: "豆角肉末", category: "小炒", price: 16, desc: "鲜香豆角和肉末的经典搭配。", ingredients: ["猪肉", "豆角", "蒜", "生抽"], techniques: ["爆炒", "煎"] },
  { id: 28, name: "肉末茄子", category: "小炒", price: 17, desc: "嫩茄子和肉末焖出香糯口感。", ingredients: ["猪肉", "茄子", "蒜", "生抽"], techniques: ["焖", "爆炒"] },
  { id: 29, name: "黑椒牛柳", category: "小炒", price: 29, desc: "黑胡椒的热烈香气和牛柳的嫩香。", ingredients: ["牛肉", "胡椒粉", "青椒", "洋葱"], techniques: ["煎", "爆炒"] },
  { id: 30, name: "豆腐青菜煲", category: "蒸菜", price: 19, desc: "清鲜豆腐与青菜，简单健康。", ingredients: ["豆腐", "青菜", "温水", "生抽"], techniques: ["焖", "炖"] },
  { id: 31, name: "蒜蓉空心菜", category: "家常菜", price: 12, desc: "蒜香简洁，saute 十分鲜脆。", ingredients: ["空心菜", "大蒜", "食用油", "盐"], techniques: ["爆炒", "煎"] },
  { id: 32, name: "照烧鸡腿", category: "硬菜", price: 24, desc: "浓厚酱香滋味，鸡腿出众。", ingredients: ["鸡腿", "生抽", "姜", "白糖"], techniques: ["烤", "焖"] },
  { id: 33, name: "砂锅豆腐", category: "汤类", price: 20, desc: "豆腐软嫩，鲜味厚重。", ingredients: ["豆腐", "鸡蛋", "温水", "青菜"], techniques: ["炖", "焖"] },
  { id: 34, name: "蜜汁地瓜", category: "家常菜", price: 14, desc: "软糯甜香，下午茶一绝。", ingredients: ["地瓜", "白糖", "盐", "油条"], techniques: ["烤", "炸"] },
  { id: 35, name: "青菜豆腐面", category: "家常菜", price: 18, desc: "面条搭配鲜嫩豆腐和青菜，更有满足感。", ingredients: ["面条", "豆腐", "青菜", "盐"], techniques: ["爆炒", "焖"] },
  { id: 36, name: "黄油蘑菇意面", category: "西餐", price: 28, desc: "奶香融入意面，面身细滑，口感浓郁。", ingredients: ["意面", "蘑菇", "黄油", "奶酪", "蒜"], techniques: ["煎", "爆炒", "焖"] },
  { id: 37, name: "黑胡椒牛排", category: "西餐", price: 42, desc: "两面焦香，黑胡椒与牛肉香气爆棚。", ingredients: ["牛排", "黑胡椒", "黄油", "蒜", "橄榄油"], techniques: ["煎", "烤", "焖"] },
  { id: 38, name: "番茄奶酪焗饭", category: "西餐", price: 24, desc: "浓郁奶香、番茄酸甜与奶酪拉丝。", ingredients: ["米饭", "番茄", "奶酪", "黄油", "洋葱"], techniques: ["烤", "焖", "煎"] },
  { id: 39, name: "香草烤鸡腿", category: "西餐", price: 26, desc: "烤到皮脆肉嫩，香草与黄油缠绵。", ingredients: ["鸡腿", "香草", "黄油", "大豆油", "姜"], techniques: ["烤", "煎", "爆炒"] },
  { id: 40, name: "培根西兰花", category: "西餐", price: 22, desc: "培根油脂融入西兰花，香脆鲜嫩。", ingredients: ["西兰花", "培根", "黄油", "蒜", "大豆油"], techniques: ["爆炒", "煎", "烤"] },
  { id: 41, name: "橄榄油番茄意面", category: "西餐", price: 27, desc: "橄榄油浓香，香草与番茄交织。", ingredients: ["意面", "番茄", "橄榄油", "蒜", "香草"], techniques: ["爆炒", "煎", "焖"] },
  { id: 42, name: "法式吐司", category: "西式主食", price: 18, desc: "外面金黄，内部松软，黄油香气醇厚。", ingredients: ["吐司", "黄油", "鸡蛋", "白糖", "牛奶"], techniques: ["煎", "烤", "炸"] },
  { id: 43, name: "芝士马铃薯饼", category: "西式主食", price: 20, desc: "外脆内软，奶酪与土豆的绝配。", ingredients: ["马铃薯", "奶酪", "黄油", "面包", "盐"], techniques: ["煎", "烤", "炸"] },
  { id: 44, name: "蒜香爆炒虾", category: "西餐", price: 33, desc: "大虾锁住鲜味，蒜香爆炒到位。", ingredients: ["大虾", "蒜", "橄榄油", "辣椒", "柠檬"], techniques: ["爆炒", "煎", "烤"] },
  { id: 45, name: "欧芹烤鱼", category: "西餐", price: 31, desc: "鱼肉嫩滑，橄榄油和欧芹提鲜。", ingredients: ["鲈鱼", "欧芹", "橄榄油", "柠檬", "蒜"], techniques: ["烤", "煎", "焖"] },
  { id: 46, name: "奶油番茄浓汤", category: "西餐", price: 19, desc: "细滑奶香与番茄酸甜的经典组合。", ingredients: ["番茄", "牛奶", "黄油", "洋葱", "盐"], techniques: ["炖", "焖", "爆炒"] },
  { id: 47, name: "西红柿鸡胸肉", category: "西餐", price: 25, desc: "番茄煨制入味，配鸡胸肉爽嫩。", ingredients: ["鸡胸肉", "西红柿", "橄榄油", "蒜", "香草"], techniques: ["煎", "炖", "焖"] },
  { id: 48, name: "香煎培根蛋", category: "西式主食", price: 17, desc: "咸香培根配嫩蛋，早餐档口必备。", ingredients: ["培根", "鸡蛋", "黄油", "面包", "盐"], techniques: ["煎", "烤", "炸"] },
  { id: 49, name: "孜然烤羊排", category: "西餐", price: 40, desc: "羊排焦香，孜然和橄榄油的味道成熟。", ingredients: ["羊排", "孜然", "橄榄油", "蒜", "胡椒粉"], techniques: ["烤", "煎", "焖"] },
  { id: 50, name: "海鲜大锅", category: "西餐", price: 36, desc: "虾、蟹、蚌与番茄海鲜汤，热闹刺激。", ingredients: ["大虾", "鲈鱼", "番茄", "橄榄油", "洋葱"], techniques: ["炖", "爆炒", "焖"] }
];

export const EXTRA_DISHES: Dish[] = [
  { id: 51, name: "松露奶油火腿面", category: "西餐", price: 32, desc: "奶油顺滑搭配火腿，浓郁松香。", ingredients: ["意面", "火腿", "奶油", "黄油", "蒜"], techniques: ["煎", "焖", "爆炒"] },
  { id: 52, name: "法式焗蘑菇", category: "西餐", price: 30, desc: "蘑菇与奶酪焗制，香气层次丰富。", ingredients: ["蘑菇", "奶酪", "黄油", "面包", "蒜"], techniques: ["烤", "焖", "煎"] },
  { id: 53, name: "香煎火鸡胸", category: "西餐", price: 35, desc: "火鸡胸嫩滑，焦香外皮和黑胡椒相得益彰。", ingredients: ["火鸡胸", "橄榄油", "黑胡椒", "柠檬", "香草"], techniques: ["煎", "烤", "焖"] },
  { id: 54, name: "蒜香烤火鸡腿", category: "西餐", price: 36, desc: "火鸡腿皮脆肉嫩，蒜香和黄油强化口感。", ingredients: ["火鸡腿", "蒜", "黄油", "橄榄油", "香草"], techniques: ["烤", "煎", "焖"] },
  { id: 55, name: "奶酪培根通心粉", category: "西式主食", price: 28, desc: "浓郁奶酪和培根完美融合。", ingredients: ["意面", "培根", "奶酪", "黄油", "牛奶"], techniques: ["焖", "煎", "烤"] },
  { id: 56, name: "奇异果柠檬海鲜饭", category: "海鲜", price: 38, desc: "酸甜鲜亮使海鲜更具层次。", ingredients: ["大虾", "鲈鱼", "柠檬", "米饭", "橄榄油"], techniques: ["烤", "煎", "焖"] },
  { id: 57, name: "番茄海鲜汤", category: "汤品", price: 26, desc: "鲜甜番茄打底，海鲜鲜味直接提升。", ingredients: ["番茄", "大虾", "鲈鱼", "温水", "洋葱"], techniques: ["炖", "煮", "焖"] },
  { id: 58, name: "金汤鸡翅煲", category: "汤品", price: 29, desc: "鸡翅在汤中慢炖，骨头鲜味浓郁。", ingredients: ["鸡翅", "姜", "温水", "白糖", "生抽"], techniques: ["炖", "焖", "煮"] },
  { id: 59, name: "西蓝花奶油汤", category: "汤品", price: 21, desc: "奶油和西蓝花做成柔和浓汤。", ingredients: ["西兰花", "牛奶", "黄油", "盐", "胡椒粉"], techniques: ["炖", "焖", "煮"] },
  { id: 60, name: "菌菇炖汤", category: "汤品", price: 23, desc: "香菇蘑菇打底，鲜味清香。", ingredients: ["蘑菇", "香菇", "温水", "盐", "姜"], techniques: ["炖", "煮", "焖"] },
  { id: 61, name: "白萝卜羊肉汤", category: "汤品", price: 32, desc: "羊肉鲜香和萝卜甜味互相映衬。", ingredients: ["羊肉", "白萝卜", "姜", "温水", "花椒"], techniques: ["炖", "煮", "焖"] },
  { id: 62, name: "豆腐鲫鱼汤", category: "汤品", price: 30, desc: "鱼鲜、豆腐滑嫩、汤汁清香。", ingredients: ["鲫鱼", "豆腐", "姜", "温水", "盐"], techniques: ["煮", "炖", "焖"] },
  { id: 63, name: "玉米排骨汤", category: "汤品", price: 27, desc: "排骨软烂，玉米香甜清爽。", ingredients: ["排骨", "玉米", "姜", "温水", "生抽"], techniques: ["炖", "煮", "焖"] },
  { id: 64, name: "番茄豆腐炖蛋", category: "汤品", price: 18, desc: "软嫩蛋花和番茄汤汁搭配更鲜。", ingredients: ["番茄", "豆腐", "鸡蛋", "温水", "盐"], techniques: ["炖", "煮", "焖"] },
  { id: 65, name: "青菜豆腐汤", category: "汤品", price: 17, desc: "清淡鲜香，适合快速下饭。", ingredients: ["青菜", "豆腐", "温水", "姜", "盐"], techniques: ["煮", "炖", "焖"] },
  { id: 66, name: "土豆炖牛肉", category: "西餐", price: 34, desc: "牛肉炖至软烂，土豆吸香。", ingredients: ["牛肉", "土豆", "洋葱", "胡萝卜", "温水"], techniques: ["炖", "焖", "煮"] },
  { id: 67, name: "黑椒起司烤土豆", category: "西式主食", price: 24, desc: "土豆外焦里软，奶酪拉丝。", ingredients: ["马铃薯", "奶酪", "黑胡椒", "黄油", "盐"], techniques: ["烤", "煎", "焖"] },
  { id: 68, name: "西红柿鸡蛋煎饼", category: "西式主食", price: 19, desc: "香脆外皮搭配番茄和鸡蛋。", ingredients: ["鸡蛋", "番茄", "面粉", "黄油", "盐"], techniques: ["煎", "烤", "炸"] },
  { id: 69, name: "燉蘑菇牛肉饭", category: "西餐", price: 39, desc: "奶香蘑菇与牛肉慢火焖成一锅。", ingredients: ["米饭", "牛肉", "蘑菇", "黄油", "洋葱"], techniques: ["焖", "炖", "煎"] },
  { id: 70, name: "香草烤龙虾", category: "海鲜", price: 46, desc: "龙虾肉质鲜甜，香草黄油做底味。", ingredients: ["龙虾", "香草", "黄油", "橄榄油", "蒜"], techniques: ["烤", "煎", "蒸"] },
  { id: 71, name: "蒜蓉烤扇贝", category: "海鲜", price: 41, desc: "扇贝香甜，蒜蓉朱香四溢。", ingredients: ["扇贝", "蒜", "黄油", "柠檬", "白糖"], techniques: ["烤", "煎", "蒸"] },
  { id: 72, name: "番茄虾仁意面", category: "西餐", price: 33, desc: "虾仁鲜甜搭配番茄酱意面。", ingredients: ["意面", "大虾", "番茄", "橄榄油", "蒜"], techniques: ["爆炒", "煎", "焖"] },
  { id: 73, name: "芝士焗海鲜饭", category: "西式主食", price: 40, desc: "海鲜与米饭加上芝士，热腾腾。", ingredients: ["米饭", "大虾", "奶酪", "黄油", "洋葱"], techniques: ["烤", "焖", "煎"] },
  { id: 74, name: "柠檬香草鱼片", category: "海鲜", price: 35, desc: "鱼片轻煎后用柠檬做鲜。", ingredients: ["鲈鱼", "柠檬", "香草", "橄榄油", "蒜"], techniques: ["煎", "烤", "蒸"] },
  { id: 75, name: "奶香玉米鸡蛋羹", category: "汤品", price: 17, desc: "玉米颗粒和蛋香混合，口感绵密。", ingredients: ["鸡蛋", "玉米", "牛奶", "温水", "盐"], techniques: ["蒸", "炖", "煮"] },
  { id: 76, name: "孜然羊肉卷", category: "西餐", price: 37, desc: "羊肉卷香气爆棚，孜然香更浓。", ingredients: ["羊肉", "孜然", "洋葱", "橄榄油", "胡椒粉"], techniques: ["烤", "煎", "焖"] },
  { id: 77, name: "香煎猪排", category: "西餐", price: 36, desc: "猪排焦香外层，肉汁丰厚。", ingredients: ["猪排", "黄油", "蒜", "黑胡椒", "盐"], techniques: ["煎", "烤", "焖"] },
  { id: 78, name: "蒜香炸鸡块", category: "西式主食", price: 30, desc: "鸡块外酥里嫩，蒜香不过火。", ingredients: ["鸡块", "大蒜", "面粉", "花生油", "盐"], techniques: ["炸", "煎", "烤"] },
  { id: 79, name: "黑椒鸡扒", category: "西餐", price: 34, desc: "鸡扒表面焦香，内部保持鲜嫩。", ingredients: ["鸡腿肉", "黑胡椒", "黄油", "橄榄油", "蒜"], techniques: ["煎", "烤", "焖"] },
  { id: 80, name: "奶油焗南瓜", category: "西餐", price: 22, desc: "南瓜绵软，奶油提香。", ingredients: ["南瓜", "奶油", "黄油", "盐", "胡椒粉"], techniques: ["烤", "焖", "煎"] },
  { id: 81, name: "锅巴豆腐汤", category: "汤品", price: 18, desc: "软豆腐和锅巴灵动，汤鲜不腻。", ingredients: ["豆腐", "锅巴", "温水", "盐", "白糖"], techniques: ["煮", "炖", "焖"] },
  { id: 82, name: "白胡椒蛤蜊汤", category: "汤品", price: 27, desc: "蛤蜊鲜甜，白胡椒香，清汤鲜。", ingredients: ["蛤蜊", "白胡椒", "姜", "温水", "蒜"], techniques: ["炖", "煮", "焖"] },
  { id: 83, name: "香菇鸡肉汤", category: "汤品", price: 24, desc: "鸡肉和菌菇慢炖，鲜味厚实。", ingredients: ["鸡腿肉", "香菇", "姜", "温水", "盐"], techniques: ["炖", "煮", "焖"] },
  { id: 84, name: "豆角焖饭", category: "西式主食", price: 23, desc: "豆角和米饭一起焖出香糯。", ingredients: ["米饭", "豆角", "黄油", "洋葱", "盐"], techniques: ["焖", "炖", "煎"] },
  { id: 85, name: "番茄焖面", category: "西式主食", price: 24, desc: "面条吸收番茄汁，香浓耐嚼。", ingredients: ["面条", "番茄", "洋葱", "黄油", "盐"], techniques: ["焖", "炖", "煎"] },
  { id: 86, name: "黄油南瓜意面", category: "西餐", price: 29, desc: "南瓜和黄油的奶香融合，口感温润。", ingredients: ["意面", "南瓜", "黄油", "奶酪", "蒜"], techniques: ["煎", "焖", "烤"] },
  { id: 87, name: "香辣花生鸡翅", category: "西餐", price: 31, desc: "花生和辣椒一起提升鸡翅香度。", ingredients: ["鸡翅", "花生", "辣椒", "黄油", "生抽"], techniques: ["烤", "爆炒", "焖"] },
  { id: 88, name: "蒜蓉焗虾", category: "海鲜", price: 35, desc: "虾肉鲜嫩，蒜蓉和黄油相互带味。", ingredients: ["大虾", "蒜", "黄油", "白糖", "柠檬"], techniques: ["烤", "蒸", "焖"] },
  { id: 89, name: "白葡萄酒炖鸡", category: "西餐", price: 38, desc: "酒香和鸡肉焦香融合，鲜味持久。", ingredients: ["鸡腿肉", "白葡萄酒", "洋葱", "香草", "黄油"], techniques: ["炖", "焖", "煎"] },
  { id: 90, name: "黑胡椒海鲜面", category: "西餐", price: 39, desc: "海鲜鲜甜与黑胡椒绵香交织。", ingredients: ["意面", "大虾", "鲈鱼", "黑胡椒", "黄油"], techniques: ["爆炒", "煎", "焖"] },
  { id: 91, name: "奶油蘑菇炖饭", category: "西式主食", price: 28, desc: "米饭吸收奶油和蘑菇的浓香。", ingredients: ["米饭", "蘑菇", "奶油", "黄油", "盐"], techniques: ["焖", "炖", "煎"] },
  { id: 92, name: "石锅豆腐鱼", category: "海鲜", price: 40, desc: "豆腐与鱼肉在石锅里互相吸味。", ingredients: ["鲈鱼", "豆腐", "姜", "大蒜", "温水"], techniques: ["焖", "炖", "蒸"] },
  { id: 93, name: "橄榄油腌鸡", category: "西餐", price: 31, desc: "腌制后烤熟，香气层层递进。", ingredients: ["鸡腿", "橄榄油", "香草", "蒜", "盐"], techniques: ["烤", "煎", "焖"] },
  { id: 94, name: "奶酪番茄焦香饼", category: "西式主食", price: 25, desc: "酸甜番茄混入奶酪，外焦内软。", ingredients: ["面包", "番茄", "奶酪", "黄油", "盐"], techniques: ["烤", "煎", "炸"] },
  { id: 95, name: "姜葱蒸龙虾", category: "海鲜", price: 48, desc: "龙虾鲜味直接锁住，姜葱提鲜。", ingredients: ["龙虾", "姜", "葱", "蒸鱼豉油", "生抽"], techniques: ["蒸", "煮", "焖"] },
  { id: 96, name: "榴莲奶油焗饭", category: "西餐", price: 33, desc: "奶香和热带风味的强烈对比。", ingredients: ["米饭", "榴莲", "奶油", "黄油", "奶酪"], techniques: ["烤", "焖", "煎"] },
  { id: 97, name: "火腿奶酪卷", category: "西式主食", price: 21, desc: "火腿和奶酪的串联爆香。", ingredients: ["火腿", "奶酪", "吐司", "黄油", "盐"], techniques: ["烤", "煎", "炸"] },
  { id: 98, name: "西红柿炖牛肉面", category: "西餐", price: 35, desc: "面条吸收醇醇牛肉汤和番茄酸香。", ingredients: ["面条", "牛肉", "西红柿", "洋葱", "温水"], techniques: ["炖", "焖", "煮"] },
  { id: 99, name: "浓汤焗菜", category: "汤品", price: 26, desc: "时蔬和浓汤分层层次丰富。", ingredients: ["西兰花", "番茄", "牛奶", "黄油", "盐"], techniques: ["焖", "炖", "烤"] },
  { id: 100, name: "黑椒鸡胸焗饭", category: "西餐", price: 32, desc: "鸡胸肉和米饭焗制后更香。", ingredients: ["米饭", "鸡胸肉", "黑胡椒", "黄油", "洋葱"], techniques: ["烤", "焖", "煎"] },
  { id: 101, name: "香蒜豆角煲", category: "家常菜", price: 20, desc: "蒜香和豆角一起提升鲜嫩。", ingredients: ["豆角", "大蒜", "食用油", "盐", "白糖"], techniques: ["焖", "爆炒", "煎"] },
  { id: 102, name: "青椒菌菇炒饭", category: "西式主食", price: 26, desc: "青椒鲜香和菌菇香浓，米饭油香。", ingredients: ["米饭", "青椒", "蘑菇", "大豆油", "盐"], techniques: ["炒", "爆炒", "煎"] },
  { id: 103, name: "咖喱海鲜虾", category: "海鲜", price: 37, desc: "咖喱酱裹住海鲜，香味层层加深。", ingredients: ["大虾", "咖喱粉", "洋葱", "大豆油", "牛奶"], techniques: ["爆炒", "焖", "煎"] },
  { id: 104, name: "奶油蒜香牛排", category: "西餐", price: 45, desc: "牛排表面焦香，奶油蒜香浓郁。", ingredients: ["牛排", "黄油", "蒜", "奶油", "黑胡椒"], techniques: ["煎", "烤", "焖"] },
  { id: 105, name: "红烧海鲜面", category: "西餐", price: 36, desc: "海鲜面集中体现鲜味和酱香。", ingredients: ["意面", "大虾", "番茄", "蒜", "橄榄油"], techniques: ["焖", "炖", "爆炒"] },
  { id: 106, name: "盐焗鸡腿", category: "西餐", price: 30, desc: "盐香锁住鸡肉汁水，外皮酥脆。", ingredients: ["鸡腿", "盐", "姜", "大豆油", "香草"], techniques: ["烤", "焖", "煎"] },
  { id: 107, name: "金黄炸土豆片", category: "西式主食", price: 18, desc: "土豆片脆口，外皮金黄酥脆。", ingredients: ["土豆", "面粉", "花生油", "盐", "白糖"], techniques: ["炸", "煎", "烤"] },
  { id: 108, name: "香菇青菜焖饭", category: "西式主食", price: 25, desc: "香菇和青菜混入米饭焖熟。", ingredients: ["米饭", "香菇", "青菜", "黄油", "生抽"], techniques: ["焖", "炖", "爆炒"] },
  { id: 109, name: "奶油白汁鱼排", category: "海鲜", price: 39, desc: "鱼排搭配白汁，面层细腻。", ingredients: ["鲈鱼", "奶油", "黄油", "白胡椒", "蒜"], techniques: ["煎", "烤", "焖"] },
  { id: 110, name: "法式洋葱汤", category: "汤品", price: 20, desc: "洋葱慢熬成奶香甘甜清汤。", ingredients: ["洋葱", "牛奶", "黄油", "盐", "面包"], techniques: ["炖", "焖", "煮"] }
];

export function emoji(name: string) {
  return EMOJIS[name] ?? "🍳";
}

export function getCategories() {
  return CATEGORIES;
}

/** 免费且无限供应的食材：不用购买、不消耗，也不计入菜名和价格。 */
export const FREE_ITEMS: string[] = ["温水"];

/** 调味类：自由烹饪起名字时不放进菜名（除非只选了调味）。 */
export const SEASONINGS: string[] = [
  "盐", "白糖", "冰糖", "醋", "生抽", "老抽", "蚝油", "豆瓣酱", "甜面酱", "番茄酱", "蒸鱼豉油",
  "香油", "辣椒油", "食用油", "大豆油", "花生油", "橄榄油", "黄油", "胡椒粉", "黑胡椒", "白胡椒",
  "花椒", "八角", "孜然", "咖喱粉", "姜汁", "香草", "欧芹", "白芝麻", "温水", "白葡萄酒"
];

/** 自由烹饪可选的烹饪方式。 */
export const COOKING_METHODS: string[] = ["炒", "爆炒", "煎", "炸", "烤", "蒸", "煮", "焖", "炖"];

/** 全部菜谱（DISHES + EXTRA_DISHES）。 */
export const ALL_DISHES: Dish[] = [...DISHES, ...EXTRA_DISHES];
